# Generated by Django 6.0.6 on 2026-08-09 08:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kod', models.CharField(max_length=32, unique=True)),
                ('nomi', models.CharField(max_length=255)),
                ('tashkilot', models.CharField(blank=True, max_length=255)),
                ('qish_boshi', models.CharField(default='09-15', help_text='MM-DD', max_length=5)),
                ('qish_oxiri', models.CharField(default='04-15', help_text='MM-DD', max_length=5)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomi', models.CharField(max_length=255)),
                ('kod', models.CharField(blank=True, help_text='Nomenklatura kodi', max_length=64)),
                ('unit', models.CharField(default='dona', max_length=32)),
                ('qishki', models.BooleanField(default=False)),
                ('narx', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('arxiv', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Buyum',
                'verbose_name_plural': 'Buyumlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomi', models.CharField(max_length=255, unique=True)),
                ('tartib', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Liniya',
                'verbose_name_plural': 'Liniyalar',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomi', models.CharField(max_length=32, unique=True)),
                ('tartib', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Oʻlchov birligi',
                'verbose_name_plural': 'Oʻlchov birliklari',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tabel', models.CharField(db_index=True, max_length=32, unique=True)),
                ('familiya', models.CharField(max_length=128)),
                ('ism', models.CharField(max_length=128)),
                ('otasi', models.CharField(blank=True, max_length=128)),
                ('sex', models.CharField(blank=True, max_length=128)),
                ('ish_joyi', models.CharField(blank=True, max_length=255)),
                ('kolonna', models.CharField(blank=True, max_length=64)),
                ('kirgan_sana', models.DateField(blank=True, null=True)),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=8)),
                ('boyi', models.IntegerField(default=0)),
                ('kiyim_olchami', models.CharField(blank=True, max_length=32)),
                ('poyabzal_olchami', models.CharField(blank=True, max_length=32)),
                ('bosh_kiyim_olchami', models.CharField(blank=True, max_length=32)),
                ('telefon', models.CharField(blank=True, max_length=32)),
                ('roles', models.JSONField(default=list, help_text='Rollar roʻyxati')),
                ('faol', models.BooleanField(default=True)),
                ('imzo_id', models.CharField(blank=True, max_length=64)),
                ('face_image', models.TextField(blank=True)),
                ('pin_hash', models.CharField(blank=True, max_length=255)),
                ('pin_reset', models.BooleanField(default=False, help_text='Keyingi kirishda majburiy yangi PIN')),
                ('is_staff', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('yoriqchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biriktirilgan', to=settings.AUTH_USER_MODEL)),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.depo')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
                'ordering': ['familiya', 'ism'],
            },
        ),
        migrations.CreateModel(
            name='AccessOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(choices=[('role', 'Rol'), ('position', 'Lavozim'), ('user', 'Foydalanuvchi')], max_length=16)),
                ('scope_id', models.CharField(help_text='Rol kodi / lavozim id / ishchi id', max_length=64)),
                ('key', models.CharField(help_text='Perm yoki FeatureKey', max_length=64)),
                ('value', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Ruxsat override',
                'verbose_name_plural': "Ruxsat override'lari",
                'unique_together': {('scope', 'scope_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ochilgan', models.DateField(default=django.utils.timezone.localdate)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MB-6 kartochka',
                'verbose_name_plural': 'MB-6 kartochkalar',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oxirgi', models.DateField()),
                ('davriylik_oy', models.IntegerField(default=12)),
                ('natija', models.CharField(choices=[('otdi', 'Oʻtdi'), ('otmadi', 'Oʻtmadi'), ('kutilmoqda', 'Kutilmoqda')], default='kutilmoqda', max_length=16)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TB imtixoni',
                'verbose_name_plural': 'TB imtixonlari',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turi', models.CharField(choices=[('tb', 'TB baxtsiz xodisa'), ('avariya', 'Avariya')], max_length=16)),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodisa',
                'verbose_name_plural': 'Xodisalar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='CardReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sana', models.DateField()),
                ('soni', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('yaroqlilik', models.IntegerField(default=0)),
                ('ishchi_imzo_id', models.CharField(blank=True, max_length=64)),
                ('ombor_imzo_id', models.CharField(blank=True, max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaytarilgan', to='core.card')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
            ],
            options={
                'verbose_name': 'Qaytarilgan buyum',
                'verbose_name_plural': 'Qaytarilgan buyumlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='CardIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sana', models.DateField()),
                ('soni', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('yaroqlilik', models.IntegerField(default=100)),
                ('imzo_id', models.CharField(blank=True, max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berilgan', to='core.card')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
            ],
            options={
                'verbose_name': 'Berilgan buyum',
                'verbose_name_plural': 'Berilgan buyumlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Kip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liniya', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('muddat_oy', models.IntegerField(default=1)),
                ('tugash', models.DateField()),
                ('imzo_id', models.CharField(blank=True, max_length=64)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kips', to=settings.AUTH_USER_MODEL)),
                ('yoriqchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bergan_kips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KIP',
                'verbose_name_plural': 'KIP yozuvlari',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tartib', models.IntegerField(default=0)),
                ('nomi', models.CharField(max_length=255)),
                ('arxiv', models.BooleanField(default=False)),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.depo')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='core.position'),
        ),
        migrations.AddField(
            model_name='worker',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='workers_multi', to='core.position'),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refresh token',
                'verbose_name_plural': 'Refresh tokenlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raqam', models.CharField(db_index=True, max_length=64, unique=True)),
                ('turi', models.CharField(choices=[('oddiy', 'Oddiy'), ('yangi_ishchi', 'Yangi ishchi')], default='oddiy', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('SUBMITTED', 'Bugalterda'), ('ACCOUNTANT_APPROVED', 'Bosh xisobchida'), ('CHIEF_APPROVED', 'Depo boshligʻida'), ('HEAD_APPROVED', 'Omborda'), ('ISSUED', 'Berildi — ishchi tasdigʻi kutilmoqda'), ('RECEIVED', 'Olindi — ombor tasdigʻi kutilmoqda'), ('COMPLETED', 'Yakunlandi'), ('REJECTED', 'Rad etildi')], db_index=True, default='SUBMITTED', max_length=32)),
                ('yaratilgan', models.DateField(default=django.utils.timezone.localdate)),
                ('yakunlangan', models.DateField(blank=True, null=True)),
                ('bug_field', models.JSONField(blank=True, default=dict)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('yaratgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soni', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='dona', max_length=32)),
                ('narx', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.request')),
            ],
            options={
                'verbose_name': 'Ariza qatori',
                'verbose_name_plural': 'Ariza qatorlari',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('journal', 'Jurnal'), ('requisition', 'Требование'), ('card', 'Kartochka'), ('kip', 'KIP')], max_length=32)),
                ('doc_id', models.CharField(db_index=True, max_length=64)),
                ('field', models.CharField(help_text='Blankadagi maydon raqami', max_length=16)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(max_length=64)),
                ('bekor', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imzo',
                'verbose_name_plural': 'Imzolar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bosqich', models.IntegerField(choices=[(1, '1-bosqich'), (2, '2-bosqich')])),
                ('sana', models.DateField()),
                ('komissiya', models.JSONField(blank=True, default=list, help_text='[{fio, lavozim}]')),
                ('nomuvofiqlik', models.TextField()),
                ('chora', models.TextField(blank=True)),
                ('masul', models.CharField(blank=True, max_length=255)),
                ('masul_lavozim', models.CharField(blank=True, max_length=255)),
                ('muddat', models.DateField()),
                ('bajarildi', models.BooleanField(default=False)),
                ('bajarilgan_izoh', models.TextField(blank=True)),
                ('imzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.signature')),
            ],
            options={
                'verbose_name': 'Jurnal yozuvi',
                'verbose_name_plural': 'Jurnal yozuvlari',
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qoldiq', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.item')),
            ],
            options={
                'verbose_name': 'Ombor qoldigʻi',
                'verbose_name_plural': 'Ombor qoldiqlari',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turi', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim')], max_length=16)),
                ('soni', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sana', models.DateField(default=django.utils.timezone.localdate)),
                ('izoh', models.CharField(blank=True, max_length=255)),
                ('hujjat_id', models.CharField(blank=True, max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='core.item')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-sana', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raqam', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('olingan', models.BooleanField(default=False)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talon',
                'verbose_name_plural': 'Talonlar',
                'ordering': ['raqam'],
            },
        ),
        migrations.CreateModel(
            name='TalonHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amal', models.CharField(choices=[('olindi', 'Olindi'), ('qaytarildi', 'Qaytarildi')], max_length=16)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('sabab', models.TextField(blank=True)),
                ('talon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarix', to='core.talon')),
                ('tb_xodim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talon tarixi',
                'verbose_name_plural': 'Talon tarixi',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('izoh', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='core.request')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holat oʻzgarishi',
                'verbose_name_plural': 'Holat oʻzgarishlari',
                'ordering': ['sana'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obyekt', models.CharField(max_length=255)),
                ('amal', models.CharField(max_length=255)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('izoh', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit jurnali',
                'ordering': ['-sana'],
                'indexes': [models.Index(fields=['-sana'], name='core_auditl_sana_021df9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turi', models.CharField(default='info', max_length=32)),
                ('sarlavha', models.CharField(max_length=255)),
                ('matn', models.TextField(blank=True)),
                ('sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('oqilgan', models.BooleanField(default=False)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-sana'],
                'indexes': [models.Index(fields=['worker', '-sana'], name='core_notifi_worker__dd7afe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muddat_oy', models.IntegerField(blank=True, help_text='Boʻsh = Ish. Chiqqun', null=True)),
                ('qishki', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='core.item')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='core.position')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normalar',
                'unique_together': {('position', 'item')},
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['tabel'], name='core_worker_tabel_6cb5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['faol', 'deleted'], name='core_worker_faol_ed6269_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', '-created_at'], name='core_reques_status_ccb3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['doc_type', 'doc_id', 'field'], name='core_signat_doc_typ_44e39d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='talon',
            unique_together={('worker', 'raqam')},
        ),
    ]
