# Generated by Django 6.0.6 on 2026-08-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='face_vector',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='worker',
            name='royxatdan_otgan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
