# Generated by Django 6.0.6 on 2026-08-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_worker_face_vector_worker_royxatdan_otgan'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='rasm',
            field=models.TextField(blank=True),
        ),
    ]
