# Generated by Django 6.0.6 on 2026-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_worker_rasm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("journal", "Jurnal"),
                    ("requisition", "Требование"),
                    ("card", "Kartochka"),
                    ("kip", "KIP"),
                    ("card_id", "ID karta"),
                ],
                max_length=32,
            ),
        ),
    ]
