# Generated by Django 6.0.6 on 2026-08-24 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_signature_doc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kolonna",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nomi", models.CharField(max_length=128, verbose_name="Kolonna nomi")),
                (
                    "turi",
                    models.CharField(
                        choices=[
                            ("elektrovoz", "Elektrovoz"),
                            ("teplovoz", "Teplovoz"),
                            ("manyovr", "Manyovr"),
                            ("yuk", "Yuk tashish"),
                            ("yolovchi", "Yoʻlovchi tashish"),
                            ("xojalik", "Xoʻjalik"),
                            ("boshqa", "Boshqa"),
                        ],
                        default="boshqa",
                        max_length=16,
                    ),
                ),
                ("izoh", models.CharField(blank=True, max_length=255)),
                ("faol", models.BooleanField(default=True)),
                (
                    "instruktor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mashinist yoʻriqchisi — bitta kolonnaga bitta instruktor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kolonnalari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kolonna",
                "verbose_name_plural": "Kolonnalar",
                "ordering": ["nomi"],
            },
        ),
        migrations.AddField(
            model_name="worker",
            name="kolonna_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Ishchi biriktirilgan kolonna",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ishchilar",
                to="core.kolonna",
            ),
        ),
    ]
