# Generated by Django 6.0.6 on 2026-08-24 17:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_kolonna_worker_kolonna_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("journal", "Jurnal"),
                    ("requisition", "Требование"),
                    ("card", "Kartochka"),
                    ("kip", "KIP"),
                    ("card_id", "ID karta"),
                    ("tnu19", "TNU-19 (depo navbatchisi)"),
                    ("yo_d26b", "Yo D-26 (instruktor yoʻriqnoma)"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Kitob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turi",
                    models.CharField(
                        choices=[
                            ("tnu19", "TNU-19 — depo navbatchisi"),
                            ("instruktor", "Yo D-26 — instruktor"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "raqam",
                    models.IntegerField(default=1, help_text="Kitob tartib raqami"),
                ),
                ("sigim", models.IntegerField(default=700, help_text="Nechta bet")),
                ("joriy_bet", models.IntegerField(default=1)),
                ("arxiv", models.BooleanField(default=False)),
                ("yopilgan", models.DateTimeField(blank=True, null=True)),
                (
                    "kolonna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kitoblar",
                        to="core.kolonna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoʻriqnoma kitobi",
                "verbose_name_plural": "Yoʻriqnoma kitoblari",
                "ordering": ["turi", "-raqam"],
            },
        ),
        migrations.CreateModel(
            name="Smena",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("kunduzgi", "Kunduzgi (08:00–20:00)"),
                            ("tungi", "Tungi (20:00–08:00)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("boshlangan", models.DateTimeField(default=django.utils.timezone.now)),
                ("tugagan", models.DateTimeField(blank=True, null=True)),
                (
                    "mazmun",
                    models.TextField(blank=True, help_text="5-ustun: qisqacha mazmun"),
                ),
                (
                    "xulosa",
                    models.TextField(
                        blank=True, help_text="6-ustun: beruvchining xulosasi"
                    ),
                ),
                ("faol", models.BooleanField(db_index=True, default=True)),
                (
                    "navbatchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smenalar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Smena",
                "verbose_name_plural": "Smenalar",
                "ordering": ["-boshlangan"],
            },
        ),
        migrations.CreateModel(
            name="YoriqnomaVaraq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bet", models.IntegerField(default=1)),
                (
                    "ishchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yoriqnoma_varaqlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kitob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varaqlar",
                        to="core.kitob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoʻriqnoma varagʻi",
                "verbose_name_plural": "Yoʻriqnoma varaqlari",
                "ordering": ["bet"],
                "unique_together": {("kitob", "ishchi")},
            },
        ),
        migrations.CreateModel(
            name="YoriqnomaYozuv",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bet", models.IntegerField(default=1)),
                ("qator", models.IntegerField(default=1)),
                ("sana", models.DateField(default=django.utils.timezone.localdate)),
                ("lavozim_qisqa", models.CharField(blank=True, max_length=32)),
                (
                    "yoriq_turi",
                    models.CharField(
                        choices=[
                            ("joriy", "JORIY"),
                            ("birlamchi", "Birlamchi"),
                            ("navbatdan", "Navbatdan tashqari"),
                            ("davriy", "Davriy"),
                        ],
                        default="joriy",
                        max_length=12,
                    ),
                ),
                ("mazmun", models.TextField(blank=True)),
                ("xulosa", models.TextField(blank=True)),
                ("beruvchi_lavozim", models.CharField(blank=True, max_length=128)),
                ("tasdiqlangan", models.BooleanField(default=False)),
                (
                    "beruvchi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beruvchi_yozuvlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beruvchi_imzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beruvchi_yozuv",
                        to="core.signature",
                    ),
                ),
                (
                    "ishchi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oluvchi_yozuvlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kitob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yozuvlar",
                        to="core.kitob",
                    ),
                ),
                (
                    "oluvchi_imzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oluvchi_yozuv",
                        to="core.signature",
                    ),
                ),
                (
                    "smena",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yozuvlar",
                        to="core.smena",
                    ),
                ),
                (
                    "varaq",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yozuvlar",
                        to="core.yoriqnomavaraq",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoʻriqnoma yozuvi",
                "verbose_name_plural": "Yoʻriqnoma yozuvlari",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kitob", "bet"], name="core_yoriqn_kitob_i_320e01_idx"
                    )
                ],
            },
        ),
    ]
