# Generated by Django 6.0.6 on 2026-09-03 09:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def zanjirlarni_ajrat(apps, schema_editor):
    """
    Mavjud tokenlarga alohida-alohida zanjir beradi.

    AddField dagi `default=uuid.uuid4` bir MARTA hisoblanadi va hamma
    eski qatorga BIR XIL qiymat yozadi. Shunday qolsa bitta ishchi
    chiqqanda oʻsha zanjirdagi barcha tokenlar — yaʼni butun serverdagi
    eski seanslar — bekor boʻlib, hamma tizimdan chiqib ketardi.
    """
    RefreshToken = apps.get_model("core", "RefreshToken")
    yangilanadi = []
    for row in RefreshToken.objects.all().only("id"):
        row.zanjir = uuid.uuid4()
        yangilanadi.append(row)
    if yangilanadi:
        RefreshToken.objects.bulk_update(yangilanadi, ["zanjir"], batch_size=500)


def orqaga(apps, schema_editor):
    """Ortga qaytishda hech nima qilinmaydi — maydonning oʻzi oʻchadi."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_signature_doc_type_kitob_smena_yoriqnomavaraq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='almashtirilgan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='oxirgi_ishlatilgan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='zanjir',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='Qurilma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qurilma_id', models.CharField(db_index=True, max_length=64)),
                ('nom', models.CharField(blank=True, max_length=120)),
                ('mobil', models.BooleanField(default=False)),
                ('ishonchli', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('oxirgi_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('oxirgi_kirish', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qurilmalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'ordering': ['-oxirgi_kirish'],
            },
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='qurilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokenlar', to='core.qurilma'),
        ),
        migrations.AddConstraint(
            model_name='qurilma',
            constraint=models.UniqueConstraint(fields=('worker', 'qurilma_id'), name='uniq_worker_qurilma'),
        ),
        migrations.RunPython(zanjirlarni_ajrat, orqaga),
    ]
