# Generated by Django 5.2.17 on 2026-09-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_refreshtoken_almashtirilgan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kip',
            name='muddat_kun',
            field=models.IntegerField(blank=True, help_text='Boʻsh = oy boʻyicha', null=True),
        ),
    ]
