# Generated by Django 6.0.6 on 2026-09-16 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedPunkt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kod', models.CharField(max_length=32, unique=True, verbose_name='Kod')),
                ('nom', models.CharField(blank=True, max_length=128, verbose_name='Nomi')),
                ('faol', models.BooleanField(default=True)),
                ('oxirgi_aloqa', models.DateTimeField(blank=True, help_text='Kiosk oxirgi marta murojaat qilgan payt', null=True)),
            ],
            options={
                'verbose_name': 'Med-punkt',
                'verbose_name_plural': 'Med-punktlar',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='Sozlama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alko_chegara_mg_l', models.FloatField(default=0.135, verbose_name='Alko chegara (aktiv), mg/L')),
                ('alko_chegara_passiv_mg_l', models.FloatField(default=0.023, verbose_name='Alko chegara (passiv), mg/L')),
                ('qon_sis_max', models.IntegerField(default=140, verbose_name='Sistolik maksimum')),
                ('qon_dia_max', models.IntegerField(default=90, verbose_name='Diastolik maksimum')),
                ('qon_puls_min', models.IntegerField(default=50, verbose_name='Puls minimum')),
                ('qon_puls_max', models.IntegerField(default=110, verbose_name='Puls maksimum')),
                ('limit_12_soat', models.IntegerField(default=5, verbose_name='12 soatda ruxsat etilgan koʻrik')),
                ('arxiv_kun', models.IntegerField(default=7, verbose_name='Arxivga oʻtish (kun)')),
                ('yangilandi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chegaralar',
                'verbose_name_plural': 'Chegaralar',
            },
        ),
        migrations.CreateModel(
            name='IshchiMeyor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sis_max', models.IntegerField(default=140)),
                ('dia_max', models.IntegerField(default=90)),
                ('puls_min', models.IntegerField(default=50)),
                ('puls_max', models.IntegerField(default=110)),
                ('izoh', models.CharField(blank=True, max_length=255)),
                ('shifokor', models.CharField(blank=True, help_text='Meʼyorni kiritgan xodim', max_length=128)),
                ('yangilandi', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medpunkt_meyor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shaxsiy meʼyor',
                'verbose_name_plural': 'Shaxsiy meʼyorlar',
                'ordering': ['worker__familiya', 'worker__ism'],
            },
        ),
        migrations.CreateModel(
            name='Hodisa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tur', models.CharField(db_index=True, max_length=32)),
                ('tabel', models.CharField(blank=True, max_length=32)),
                ('sessiya_id', models.CharField(blank=True, max_length=64)),
                ('tafsilot', models.CharField(blank=True, max_length=255)),
                ('vaqt', models.DateTimeField(db_index=True)),
                ('korildi', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medpunkt_hodisalari', to=settings.AUTH_USER_MODEL)),
                ('med_punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodisalar', to='medpunkt.medpunkt')),
            ],
            options={
                'verbose_name': 'Kiosk hodisasi',
                'verbose_name_plural': 'Kiosk hodisalari',
                'ordering': ['-vaqt'],
            },
        ),
        migrations.CreateModel(
            name='Olchov',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tabel', models.CharField(blank=True, db_index=True, help_text='Kioskdagi tabel/karta ID', max_length=32)),
                ('sessiya_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tur', models.CharField(choices=[('alko', 'Alkotester'), ('qon', 'Qon bosimi')], max_length=8)),
                ('qurilma', models.CharField(blank=True, help_text='Model/seriya raqami', max_length=64)),
                ('unik_kalit', models.CharField(max_length=128, unique=True)),
                ('olchov_vaqti', models.DateTimeField(db_index=True)),
                ('qiymatlar', models.JSONField(default=dict, help_text='Xom natija: mg_l/aktiv yoki sistolik/diastolik/puls')),
                ('tasdiq', models.JSONField(default=dict, help_text='{qr, face, surat} — tekshirilmagan boʻlsa null')),
                ('face_masofa', models.FloatField(blank=True, null=True)),
                ('egasiz', models.BooleanField(default=False, help_text='Sessiyasiz (QR skanersiz) oʻlchov')),
                ('holat', models.CharField(choices=[('normal', 'Meʼyorda'), ('flagged', 'Meʼyordan chetda'), ('egasiz', 'Xodim aniqlanmagan')], db_index=True, default='normal', max_length=8)),
                ('izoh', models.CharField(blank=True, help_text='Server xulosasi', max_length=255)),
                ('arxivlangan', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('med_punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olchovlar', to='medpunkt.medpunkt')),
                ('worker', models.ForeignKey(blank=True, help_text='Tabel boʻyicha topilgan xodim (topilmasa — boʻsh)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medpunkt_olchovlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oʻlchov',
                'verbose_name_plural': 'Oʻlchovlar',
                'ordering': ['-olchov_vaqti'],
            },
        ),
    ]
